default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  database: kantan-register_development

  # ▼ 追加 ▼  「DB内部の時刻は常に UTC」という前提なら安全
  # variables:
    # time_zone: "+00:00"

test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  database: kantan-register_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  # 以下はオプションの最適化設定
  prepared_statements: true
  statement_limit: 200