default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  database: kantan-register_development

test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  database: kantan-register_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  # 以下はオプションの最適化設定
  prepared_statements: true
  statement_limit: 200